"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path

######### Part 11.4: Configure settings.py for Production ########
import os
import dj_database_url
import stripe



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!



# SECRET_KEY = 'django-insecure-o&a+tm@ie)6iull_gwe_cduze65kh0w!5^095)7e!01qyd1d(e'
######### Part 11.4: Configure settings.py for Production ########
SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = 'True'
######### Part 11.4: Configure settings.py for Production ########
DEBUG = os.environ.get('DEBUG', 'False') == 'True'




# ALLOWED_HOSTS = []

######### Part 11.4: Configure settings.py for Production ########
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 

    ############ App Created ################
    'myapp',

    ############ Third-Party Apps ##########
    'django_recaptcha',
    'rest_framework',
    # 'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # <--- This is where you can add project-wide template directories
        'APP_DIRS': True, # <--- This is crucial for app-specific templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3', 
        conn_max_age=600 
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

######### Part 11.4: Configure settings.py for Production ########
# NEW: Configuration for serving static files in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


######### Part 11.4: Configure settings.py for Production ########
# NEW: Redirect all HTTP requests to HTTPS
# This is crucial for security in production. Render handles SSL automatically.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


######### Part 11.4: Configure settings.py for Production ########
# NEW: Optional: If you want to use Django's built-in messages framework with Bootstrap
# from django.contrib.messages import constants as messages
# MESSAGE_TAGS = {
#     messages.DEBUG: 'alert-info',
#     messages.INFO: 'alert-info',
#     messages.SUCCESS: 'alert-success',
#     messages.WARNING: 'alert-warning',
#     messages.ERROR: 'alert-danger',
# }



################################# Media Section ################################

# Media files (user-uploaded content)
MEDIA_URL = '/media/' # <--- The URL prefix for serving media files
# Logic & Imagination: This is the magical address prefix for all your user-uploaded
# enchanted portraits and artifacts. It tells the browser, "Look for these dynamic
# visual elements by starting at this 'media' magical pathway."

MEDIA_ROOT = BASE_DIR / 'media' # <--- The absolute path to the directory where uploaded files will be stored
# Logic & Imagination: This is the designated, physical storage chamber within your
# laboratory's vault where all the user-uploaded magical items will be kept.
# BASE_DIR ensures it's relative to your project root.



# RECAPTCHA_PUBLIC_KEY  = "6LcLQ38rAAAAABMUb_jyoKb5C_S3mZNV0yQXNjjN"               # <--- Replace with your actual Site Key
# RECAPTCHA_PRIVATE_KEY = "6LcLQ38rAAAAAI9dn5LfFz0k5wh_K4S__C-DiKlK" 

######### Part 11.4: Configure settings.py for Production ########
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY') # MODIFIED
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY') # MODIFIED


   #<--- Replace with your actual Secret Key






# SILENCED_SYSTEM_CHECKS = [
#     'django_recaptcha.recaptcha_test_key_error',
# ]



# Authentication Redirect URLs
LOGIN_REDIRECT_URL = '/' # Where to redirect after successful login
# Logic & Imagination: After a customer successfully presents their Access Amulet,
# the doorkeeper automatically guides them to the main product catalog.

LOGOUT_REDIRECT_URL = '/' # Where to redirect after successful logout
# Logic & Imagination: After a customer relinquishes their Amulet, they are
# guided back to the public entrance of the product catalog.


# URL to redirect to when a user is not logged in and tries to access a login_required view
LOGIN_URL = '/login/' # <--- NEW: Define where login_required redirects!
# Logic & Imagination: This tells all the basic magical wards: "If you encounter
# a traveler without an Access Amulet, send them to THIS specific login portal."



# NEW: Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', # For browser-based API access (logged-in users)
        'rest_framework.authentication.BasicAuthentication',   # For simple username/password authentication
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly', # NEW: Allows authenticated users full access,
                                                               # but unauthenticated users can only read (GET)
    ],
    # Optionally, enable the browsable API renderer for easy testing in browser
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}


# NEW: Channels ASGI application
# ASGI_APPLICATION = 'mysite.asgi.application'


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)], # Default Redis host and port
#         },
#     },
# }

######### Part 11.4: Configure settings.py for Production ########

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
#         'CONFIG': {
#             "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')], # MODIFIED: Read Redis URL from env var
#         },
#     },
# }





############################ Stripe Payment ###########################


STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY') 

stripe.api_key = STRIPE_SECRET_KEY



